#!/bin/bash -L

#SBATCH - A g2018003
#SBATCH - p core
#SBATCH - n 2
#SBATCH - t 02:30:00
#SBATCH - J genome_assembly_WGS
#SBATCH -- mail-type=ALL
#SBATCH -- mail-user amanj.bajalan.6489@student.uu.se

# Load modules
module load bioinfo-tools
module soapdenovo

# Commands
./soapdenovo all -s config_file -K 49 -o soapdenovoK49_result

