#!/bin/bash -L

#SBATCH - A g2018003
#SBATCH - p core
#SBATCH - n 2
#SBATCH - t 00:10:00
#SBATCH - J RNA_trimmed_read_quality
#SBATCH -- mail-type=ALL
#SBATCH -- mail-user amanj.bajalan.6489@student.uu.se

# Load modules
module load bioinfo-tools
module load FastQC

# Commands
fastqc ./1_trimmed_DATA.fastq

